# Generated by Django 5.0.6 on 2025-02-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociado', '0001_initial'),
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Parentesco',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Coohoperativitos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('tipoDocumento', models.CharField(choices=[('CEDULA', 'Cedula'), ('REGISTRO CIVIL', 'Registro Civil'), ('TARJETA IDENTIDAD', 'Tarjeta Identidad'), ('CEDULA EXTRANJERA', 'Cedula Extranjera'), ('PASAPORTE', 'Pasaporte'), ('PPT', 'PPT')], default='CEDULA', verbose_name='Tipo Documento')),
                ('numDocumento', models.CharField(max_length=10, verbose_name='Número Documento')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaNacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechaRetiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Coohoperativitos',
                'verbose_name_plural': 'Coohoperativitos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato')], default='PERRO', max_length=30, verbose_name='Tipo')),
                ('raza', models.CharField(max_length=30, verbose_name='Raza')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('vacunasCompletas', models.BooleanField(verbose_name='Vacunas Completas')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechaRetiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Mascota',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('tipoDocumento', models.CharField(choices=[('CEDULA', 'Cedula'), ('REGISTRO CIVIL', 'Registro Civil'), ('TARJETA IDENTIDAD', 'Tarjeta Identidad'), ('CEDULA EXTRANJERA', 'Cedula Extranjera'), ('PASAPORTE', 'Pasaporte'), ('PPT', 'PPT')], default='CEDULA', verbose_name='Tipo Documento')),
                ('numDocumento', models.CharField(max_length=12, verbose_name='Número Documento')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('repatriacion', models.BooleanField(verbose_name='Repatriacion')),
                ('fechaRepatriacion', models.DateField(blank=True, null=True, verbose_name='Fecha Repatriacion')),
                ('ciudadRepatriacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad Repatriación')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechaRetiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('paisRepatriacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='departamento.paisrepatriacion')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='beneficiario.parentesco')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'ordering': ['pk'],
            },
        ),
    ]
