# Generated by Django 5.0.6 on 2025-10-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0001_initial'),
        ('parametro', '0005_alter_consecutivoradicado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='primerMesRepatriacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='beneficiarios_repatriacion', to='parametro.mestarifa'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='primerMes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mascotas', to='parametro.mestarifa'),
        ),
    ]
