# Generated by Django 5.0.6 on 2024-07-24 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0001_initial'),
        ('departamento', '0002_paisrepatriacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='paisRepatriacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='departamento.paisrepatriacion'),
        ),
    ]
