# Generated by Django 5.0.6 on 2024-07-26 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0003_remove_asociado_deptodoc'),
        ('beneficiario', '0002_beneficiario_paisrepatriacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coohoperativitos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('tipoDocumento', models.CharField(choices=[('CEDULA', 'Cedula'), ('REGISTRO CIVIL', 'Registro Civil'), ('TARJETA IDENTIDAD', 'Tarjeta Identidad'), ('CEDULA EXTRANJERA', 'Cedula Extranjera'), ('PASAPORTE', 'Pasaporte')], default='CEDULA', verbose_name='Tipo Documento')),
                ('numDocumento', models.CharField(max_length=10, verbose_name='Número Documento')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechaRetiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Coohoperativitos',
                'verbose_name_plural': 'Coohoperativitos',
                'ordering': ['pk'],
            },
        ),
    ]
