# Generated by Django 5.0.6 on 2026-03-25 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0002_beneficiario_primermesrepatriacion_mascota_primermes'),
        ('parametro', '0008_rename_porcentajedescuentoanticipo_porcentajeanticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coohoperativitos',
            name='primerMes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='coohoperativitos', to='parametro.mestarifa'),
        ),
    ]
