# Generated by Django 5.0.6 on 2026-03-27 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0003_coohoperativitos_primermes'),
        ('parametro', '0008_rename_porcentajedescuentoanticipo_porcentajeanticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='fechaRetiroRepatriacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='ultimoMesRepatriacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='beneficiarios_retiro_repatriacion', to='parametro.mestarifa'),
        ),
    ]
