# Generated by Django 5.0.6 on 2024-10-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0003_alter_beneficiario_numdocumento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentesco',
            options={'ordering': ['nombre'], 'verbose_name': 'Parentesco'},
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='tipoDocumento',
            field=models.CharField(choices=[('CEDULA', 'Cedula'), ('REGISTRO CIVIL', 'Registro Civil'), ('TARJETA IDENTIDAD', 'Tarjeta Identidad'), ('CEDULA EXTRANJERA', 'Cedula Extranjera'), ('PASAPORTE', 'Pasaporte'), ('PPT', 'PPT')], default='CEDULA', verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='coohoperativitos',
            name='tipoDocumento',
            field=models.CharField(choices=[('CEDULA', 'Cedula'), ('REGISTRO CIVIL', 'Registro Civil'), ('TARJETA IDENTIDAD', 'Tarjeta Identidad'), ('CEDULA EXTRANJERA', 'Cedula Extranjera'), ('PASAPORTE', 'Pasaporte'), ('PPT', 'PPT')], default='CEDULA', verbose_name='Tipo Documento'),
        ),
    ]
