# Generated by Django 5.0.6 on 2026-04-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0004_beneficiario_fecharetirorepatriacion_and_more'),
        ('parametro', '0008_rename_porcentajedescuentoanticipo_porcentajeanticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='ultimoMes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mascotas_retiro', to='parametro.mestarifa'),
        ),
    ]
