# Generated by Django 5.0.6 on 2024-11-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0004_alter_parentesco_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='fechaRepatriacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Repatriacion'),
        ),
    ]
