# Generated by Django 5.0.6 on 2024-11-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0005_beneficiario_fecharepatriacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coohoperativitos',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
    ]
