# Generated by Django 5.0.6 on 2026-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0005_mascota_ultimomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
