# Generated by Django 5.0.6 on 2026-04-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0006_mascota_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
