# Generated by Django 5.0.6 on 2025-02-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('indicativo', models.CharField(max_length=10)),
                ('bandera', models.URLField()),
            ],
        ),
    ]
