# Generated by Django 5.0.6 on 2024-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaisRepatriacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Pais Repatriación',
                'verbose_name_plural': 'Pais Repatriación',
                'ordering': ['pk'],
            },
        ),
    ]
