# Generated by Django 5.0.6 on 2025-02-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['pk'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Pais'},
        ),
    ]
