# Generated by Django 5.0.6 on 2024-12-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoventa',
            name='formaPago',
            field=models.CharField(choices=[('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO')], default='CONTADO'),
        ),
        migrations.AddField(
            model_name='historicoventa',
            name='valorBruto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicoventa',
            name='valorNeto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
