# Generated by Django 5.0.6 on 2025-03-28 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0002_formapago_estadoregistro'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoventa',
            name='tasaInteres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametro.tasasinterescredito'),
        ),
        migrations.AlterField(
            model_name='historicoventa',
            name='formaPago',
            field=models.CharField(choices=[('CREDITO', 'CREDITO'), ('CONTADO', 'CONTADO'), ('DESCUENTO NOMINA', 'DESCUENTO NOMINA')], default='CREDITO'),
        ),
    ]
