# Generated by Django 5.0.6 on 2025-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_historicoventa_tasainteres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoventa',
            name='formaPago',
            field=models.CharField(choices=[('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO'), ('DESCUENTO NOMINA', 'DESCUENTO NOMINA')], default='CREDITO'),
        ),
    ]
