# Generated by Django 5.0.6 on 2024-12-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_historicoventa_formapago_historicoventa_valorbruto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoventa',
            name='cuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
