# Generated by Django 5.0.6 on 2024-12-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_historicoventa_cuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoventa',
            name='pendientePago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
