# Generated by Django 5.0.6 on 2025-11-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0005_alter_consecutivoradicado_options_and_more'),
        ('ventas', '0003_alter_historicoventa_formapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoventa',
            name='primerMes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historico_ventas', to='parametro.mestarifa'),
        ),
    ]
