# Generated by Django 5.0.6 on 2024-12-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_historicoventa_pendientepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoventa',
            name='formaPago',
            field=models.CharField(choices=[('CREDITO', 'CREDITO'), ('CONTADO', 'CONTADO')], default='CONTADO'),
        ),
    ]
