# Generated by Django 5.0.6 on 2024-12-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_historicoventa_formapago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='descuento',
        ),
        migrations.AddField(
            model_name='historicoventa',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
