# Generated by Django 5.0.6 on 2024-12-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_remove_detalleventa_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
    ]
