# Generated by Django 5.0.6 on 2024-12-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_remove_producto_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorcentajeDescuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=3)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
