# Generated by Django 5.0.6 on 2024-12-20 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_porcentajedescuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoventa',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.porcentajedescuento'),
        ),
    ]
