# Generated by Django 5.0.6 on 2025-01-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_historicoventa_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoventa',
            name='valorCuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicoventa',
            name='valorDescuento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
