# Generated by Django 5.0.6 on 2025-01-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_historicoventa_valorcuotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoventa',
            name='cuotasPagas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
