# Generated by Django 5.0.6 on 2026-04-21 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginBlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_until', models.DateTimeField()),
                ('reason', models.CharField(default='rate_limit', max_length=50)),
                ('unlock_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('attempts_count', models.IntegerField(default=0)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unlocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueo de Login',
                'verbose_name_plural': 'Bloqueos de Login',
                'ordering': ['-blocked_at'],
            },
        ),
    ]
