# Generated by Django 5.0.6 on 2025-02-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioasociado',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuarioasociado',
            name='verification_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
