# Generated by Django 5.0.6 on 2025-02-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociado', '0001_initial'),
        ('parametro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAuxilio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('entidadBancaria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Entidad Bancaria')),
                ('numCuenta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número Cuenta')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('estado', models.CharField(choices=[('REVISION', 'REVISION'), ('OTORGADO', 'OTORGADO'), ('DENEGADO', 'DENEGADO')], default='REVISION', verbose_name='Estado')),
                ('nombre', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nombre')),
                ('numDoc', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número Documento')),
                ('nivelEducativo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nivel Educativo')),
                ('anexoOne', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 1')),
                ('anexoTwo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 2')),
                ('anexoThree', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 3')),
                ('anexoFour', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 4')),
                ('anexoFive', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 5')),
                ('anexoSix', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 6')),
                ('anexoSeven', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 7')),
                ('anexoEight', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 8')),
                ('observacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('motivoEliminacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo de Eliminacion')),
                ('fechaDesembolso', models.DateField(blank=True, null=True, verbose_name='Fecha Desembolso')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historial de Auxilios',
                'verbose_name_plural': 'Historial de Auxilios',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoCredito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('lineaCredito', models.CharField(choices=[('ANTICIPO NOMINA', 'ANTICIPO NOMINA'), ('SOLUCION INMEDIATA', 'SOLUCION INMEDIATA'), ('CREDILIBRE', 'CREDILIBRE'), ('CREDICONTIGO', 'CREDICONTIGO'), ('KUPI', 'KUPI'), ('CREDISEGURO', 'CREDISEGURO'), ('CREDITO SOAT', 'CREDITO SOAT')], default='SOLUCION INMEDIATA', verbose_name='Linea Credito')),
                ('amortizacion', models.CharField(choices=[('CUOTA FIJA', 'CUOTA FIJA'), ('CUOTA VARIABLE', 'CUOTA VARIABLE')], default='CUOTA FIJA', verbose_name='Amortización')),
                ('cuotas', models.IntegerField(verbose_name='Cuotas')),
                ('valorCuota', models.IntegerField(verbose_name='Valor Cuota')),
                ('totalCredito', models.IntegerField(verbose_name='Total Credito')),
                ('medioPago', models.CharField(choices=[('PAGO DIRECTO', 'PAGO DIRECTO'), ('NOMINA', 'NOMINA'), ('LIBRANZA', 'LIBRANZA')], default='PAGO DIRECTO', verbose_name='Medio de Pago')),
                ('formaDesembolso', models.CharField(choices=[('TRANSFERENCIA ELECTRONICA', 'TRANSFERENCIA ELECTRONICA'), ('CHEQUE', 'CHEQUE'), ('CUENTA AHORROS', 'CUENTA AHORROS')], default='TRANSFERENCIA ELECTRONICA', verbose_name='Forma de Desembolso')),
                ('estado', models.CharField(choices=[('REVISION', 'REVISION'), ('OTORGADO', 'OTORGADO'), ('DENEGADO', 'DENEGADO')], default='REVISION', verbose_name='Estado')),
                ('banco', models.CharField(blank=True, max_length=30, null=True, verbose_name='Banco')),
                ('numCuenta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero Cuenta')),
                ('tipoCuenta', models.CharField(blank=True, choices=[('CUENTA AHORROS', 'CUENTA AHORROS'), ('CUENTA CORRIENTE', 'CUENTA CORRIENTE')], null=True, verbose_name='Tipo Cuenta')),
                ('cuotasPagas', models.IntegerField(blank=True, null=True)),
                ('pendientePago', models.IntegerField(blank=True, null=True)),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historial de Creditos',
                'verbose_name_plural': 'Historial de Creditos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSeguroVida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorPago', models.IntegerField(verbose_name='Valor Pago')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechaRetiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seguro Vida',
                'verbose_name_plural': 'Seguro Vida',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('valorPago', models.IntegerField(verbose_name='Valor Pago')),
                ('aportePago', models.IntegerField(verbose_name='Aporte')),
                ('bSocialPago', models.IntegerField(verbose_name='Bienestar Social')),
                ('mascotaPago', models.IntegerField(blank=True, null=True, verbose_name='Mascota')),
                ('repatriacionPago', models.IntegerField(blank=True, null=True, verbose_name='Repatriacion')),
                ('seguroVidaPago', models.IntegerField(blank=True, null=True, verbose_name='Seguro Vida')),
                ('adicionalesPago', models.IntegerField(blank=True, null=True, verbose_name='Adicionales')),
                ('coohopAporte', models.IntegerField(blank=True, null=True, verbose_name='Coohoperativitos Aporte')),
                ('coohopBsocial', models.IntegerField(blank=True, null=True, verbose_name='Coohoperativitos B Social')),
                ('convenioPago', models.IntegerField(blank=True, null=True, verbose_name='Convenio')),
                ('creditoHomeElements', models.IntegerField(verbose_name='Credito Home Elements')),
                ('credito', models.IntegerField(blank=True, null=True, verbose_name='Credito')),
                ('diferencia', models.IntegerField(blank=True, null=True, verbose_name='Diferencia')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.formapago')),
                ('mesPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.mestarifa')),
            ],
            options={
                'verbose_name': 'Historial de Pagos',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['pk'],
            },
        ),
    ]
