# Generated by Django 5.0.6 on 2024-07-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociado', '0003_remove_asociado_deptodoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAuxilio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('estado', models.CharField(choices=[('OTORGADO', 'Otorgado'), ('DENEGADO', 'Denegado')], default='OTORGADO', verbose_name='Estado')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Historial de Auxilios',
                'verbose_name_plural': 'Historial de Auxilios',
                'ordering': ['pk'],
            },
        ),
    ]
