# Generated by Django 5.0.6 on 2024-09-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociado', '0001_initial'),
        ('beneficiario', '0001_initial'),
        ('parametro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorPago', models.IntegerField(verbose_name='Valor Pago')),
                ('aportePago', models.IntegerField(verbose_name='Aporte')),
                ('bSocialPago', models.IntegerField(verbose_name='Bienestar Social')),
                ('mascotaPago', models.IntegerField(blank=True, null=True, verbose_name='Mascota')),
                ('repatriacionPago', models.IntegerField(blank=True, null=True, verbose_name='Repatriacion')),
                ('seguroVidaPago', models.IntegerField(blank=True, null=True, verbose_name='Seguro Vida')),
                ('adicionalesPago', models.IntegerField(blank=True, null=True, verbose_name='Adicionales')),
                ('coohopAporte', models.IntegerField(blank=True, null=True, verbose_name='Coohoperativitos Aporte')),
                ('coohopBsocial', models.IntegerField(blank=True, null=True, verbose_name='Coohoperativitos B Social')),
                ('diferencia', models.IntegerField(blank=True, null=True, verbose_name='Diferencia')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.formapago')),
                ('mesPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.mestarifa')),
            ],
            options={
                'verbose_name': 'Historial de Pagos',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAuxilio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('estado', models.CharField(choices=[('REVISION', 'REVISION'), ('OTORGADO', 'OTORGADO'), ('DENEGADO', 'DENEGADO')], default='REVISION', verbose_name='Estado')),
                ('nombre', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nombre')),
                ('numDoc', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número Documento')),
                ('nivelEducativo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nivel Educativo')),
                ('anexoOne', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 1')),
                ('anexoTwo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 2')),
                ('anexoThree', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 3')),
                ('anexoFour', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 4')),
                ('anexoFive', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 5')),
                ('anexoSix', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 6')),
                ('anexoSeven', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 7')),
                ('anexoEight', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 8')),
                ('fechaDesembolso', models.DateField(blank=True, null=True, verbose_name='Fecha Desembolso')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('parentesco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='beneficiario.parentesco')),
                ('tipoAuxilio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.tipoauxilio')),
            ],
            options={
                'verbose_name': 'Historial de Auxilios',
                'verbose_name_plural': 'Historial de Auxilios',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoCredito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('cuotas', models.IntegerField(verbose_name='Cuotas')),
                ('estado', models.CharField(choices=[('REVISION', 'REVISION'), ('OTORGADO', 'OTORGADO'), ('DENEGADO', 'DENEGADO')], default='REVISION', verbose_name='Estado')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Historial de Creditos',
                'verbose_name_plural': 'Historial de Creditos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSeguroVida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorPago', models.IntegerField(verbose_name='Valor Pago')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechaRetiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Seguro Vida',
                'verbose_name_plural': 'Seguro Vida',
                'ordering': ['pk'],
            },
        ),
    ]
