# Generated by Django 5.0.6 on 2025-03-17 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociado', '0001_initial'),
        ('beneficiario', '0001_initial'),
        ('historico', '0001_initial'),
        ('parametro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpagos',
            name='userCreacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialpagos',
            name='userModificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='parentesco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='beneficiario.parentesco'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='tipoAuxilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.tipoauxilio'),
        ),
        migrations.AddField(
            model_name='historicocredito',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado'),
        ),
        migrations.AddField(
            model_name='historicocredito',
            name='tasaInteres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametro.tasasinterescredito'),
        ),
        migrations.AddField(
            model_name='historicosegurovida',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado'),
        ),
    ]
