# Generated by Django 5.0.6 on 2024-09-27 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpagos',
            name='fechaPago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pago'),
        ),
        migrations.AddField(
            model_name='historialpagos',
            name='userCreacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialpagos',
            name='userModificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
