# Generated by Django 5.0.6 on 2024-07-22 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0003_remove_asociado_deptodoc'),
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoauxilio',
            name='estado',
            field=models.CharField(choices=[('REVISION', 'Revision'), ('OTORGADO', 'Otorgado'), ('DENEGADO', 'Denegado')], default='REVISION', verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='HistoricoCredito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSolicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('cuotas', models.IntegerField(verbose_name='Valor')),
                ('estado', models.CharField(choices=[('REVISION', 'Revision'), ('OTORGADO', 'Otorgado'), ('DENEGADO', 'Denegado')], default='REVISION', verbose_name='Estado')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Historial de Auxilios',
                'verbose_name_plural': 'Historial de Auxilios',
                'ordering': ['pk'],
            },
        ),
    ]
