# Generated by Django 5.0.6 on 2024-09-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarifaAsociado',
        ),
    ]
