# Generated by Django 5.0.6 on 2024-07-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0002_alter_historicoauxilio_estado_historicocredito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicocredito',
            options={'ordering': ['pk'], 'verbose_name': 'Historial de Creditos', 'verbose_name_plural': 'Historial de Creditos'},
        ),
        migrations.AlterField(
            model_name='historicocredito',
            name='cuotas',
            field=models.IntegerField(verbose_name='Cuotas'),
        ),
    ]
