# Generated by Django 5.0.6 on 2025-04-09 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_historialpagos_ventahe'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpagos',
            name='creditoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagosCredito', to='historico.historicocredito'),
        ),
    ]
