# Generated by Django 5.0.6 on 2024-11-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_historialpagos_adicionalesfecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpagos',
            name='adicionalesFecha',
        ),
        migrations.RemoveField(
            model_name='historialpagos',
            name='coohopFecha',
        ),
        migrations.RemoveField(
            model_name='historialpagos',
            name='mascotaFecha',
        ),
        migrations.RemoveField(
            model_name='historialpagos',
            name='repatriacionFecha',
        ),
        migrations.RemoveField(
            model_name='historialpagos',
            name='seguroVidaFecha',
        ),
    ]
