# Generated by Django 5.0.6 on 2024-07-24 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0003_remove_asociado_deptodoc'),
        ('historico', '0004_tarifaasociado'),
        ('parametro', '0004_mestarifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorPago', models.IntegerField(verbose_name='Valor Pago')),
                ('aportePago', models.IntegerField(verbose_name='Aporte')),
                ('bSocialPago', models.IntegerField(verbose_name='Bienestar Social')),
                ('mascotaPago', models.IntegerField(blank=True, null=True, verbose_name='Mascota')),
                ('repatriacionPago', models.IntegerField(blank=True, null=True, verbose_name='Repatriacion')),
                ('seguroVidaPago', models.IntegerField(blank=True, null=True, verbose_name='Seguro Vida')),
                ('adicionalesPago', models.IntegerField(blank=True, null=True, verbose_name='Adicionales')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('mesPago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.mestarifa')),
            ],
            options={
                'verbose_name': 'Historial de Pagos',
                'verbose_name_plural': 'Historial de Pagos',
                'ordering': ['pk'],
            },
        ),
    ]
