# Generated by Django 5.0.6 on 2024-07-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0005_historialpagos'),
        ('parametro', '0005_formapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpagos',
            name='FormaPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametro.formapago'),
        ),
    ]
