# Generated by Django 5.0.6 on 2025-08-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0006_conveniohistoricogasolina_asociado'),
        ('historico', '0005_alter_historialpagos_creditohomeelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpagos',
            name='convenio_gasolina_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagosGasolina', to='asociado.conveniohistoricogasolina'),
        ),
    ]
