# Generated by Django 5.0.6 on 2024-11-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0005_historicoauxilio_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoauxilio',
            name='entidadBancaria',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Entidad Bancaria'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='numCuenta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número Cuenta'),
        ),
    ]
