# Generated by Django 5.0.6 on 2024-07-24 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0006_historialpagos_formapago'),
        ('parametro', '0005_formapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpagos',
            name='FormaPago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='parametro.formapago'),
            preserve_default=False,
        ),
    ]
