# Generated by Django 5.0.6 on 2025-08-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0006_historialpagos_convenio_gasolina_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoauxilio',
            name='nivelEducativo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel Educativo'),
        ),
    ]
