# Generated by Django 5.0.6 on 2024-12-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0007_historicoauxilio_motivoeliminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpagos',
            name='convenioPago',
            field=models.IntegerField(blank=True, null=True, verbose_name='Convenio'),
        ),
    ]
