# Generated by Django 5.0.6 on 2025-10-29 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0007_alter_historicoauxilio_niveleducativo'),
        ('parametro', '0005_alter_consecutivoradicado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosegurovida',
            name='primerMesSeguroVida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historico_seguro_vida', to='parametro.mestarifa'),
        ),
    ]
