# Generated by Django 5.0.6 on 2024-07-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0007_alter_historialpagos_formapago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialpagos',
            old_name='FormaPago',
            new_name='formaPago',
        ),
    ]
