# Generated by Django 5.0.6 on 2025-11-10 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0008_historicosegurovida_primermessegurovida'),
        ('parametro', '0005_alter_consecutivoradicado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocredito',
            name='primerMes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historico_creditos', to='parametro.mestarifa'),
        ),
    ]
