# Generated by Django 5.0.6 on 2024-07-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0008_rename_formapago_historialpagos_formapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaasociado',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
