# Generated by Django 5.0.6 on 2026-04-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0009_historicocredito_primermes'),
        ('parametro', '0008_rename_porcentajedescuentoanticipo_porcentajeanticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosegurovida',
            name='ultimoMesSeguroVida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historico_seguro_vida_retiro', to='parametro.mestarifa'),
        ),
    ]
