# Generated by Django 5.0.6 on 2024-07-26 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0003_remove_asociado_deptodoc'),
        ('historico', '0009_tarifaasociado_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSeguroVida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorPago', models.IntegerField(verbose_name='Valor Pago')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Seguro Vida',
                'verbose_name_plural': 'Seguro Vida',
                'ordering': ['pk'],
            },
        ),
    ]
