# Generated by Django 5.0.6 on 2025-01-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0009_historicopagoshomeelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicopagoshomeelements',
            name='fechaPago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pago'),
        ),
    ]
