# Generated by Django 5.0.6 on 2025-01-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0010_historicopagoshomeelements_fechapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpagos',
            name='creditoHomeElements',
            field=models.IntegerField(blank=True, null=True, verbose_name='Credito Home Elements'),
        ),
        migrations.DeleteModel(
            name='HistoricoPagosHomeElements',
        ),
    ]
