# Generated by Django 5.0.6 on 2026-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0010_historicosegurovida_ultimomessegurovida'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosegurovida',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
