# Generated by Django 5.0.6 on 2024-07-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0010_historicosegurovida'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaasociado',
            name='cuotaCoohopAporte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coohoperativito Aporte'),
        ),
        migrations.AddField(
            model_name='tarifaasociado',
            name='cuotaCoohopBsocial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coohoperativito Bienestar Social'),
        ),
    ]
