# Generated by Django 5.0.6 on 2024-07-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0011_tarifaasociado_cuotacoohopaporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpagos',
            name='coohopAporte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coohoperativitos Aporte'),
        ),
        migrations.AddField(
            model_name='historialpagos',
            name='coohopBsocial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coohoperativitos B Social'),
        ),
    ]
