# Generated by Django 5.0.6 on 2024-07-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0012_historialpagos_coohopaporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosegurovida',
            name='fechaRetiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Retiro'),
        ),
    ]
