# Generated by Django 5.0.6 on 2025-01-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0012_alter_historialpagos_creditohomeelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocredito',
            name='lineaCredito',
            field=models.CharField(choices=[('ANTICIPO NOMINA', 'ANTICIPO NOMINA'), ('SOLUCION INMEDIATA', 'SOLUCION INMEDIATA'), ('CREDILIBRE', 'CREDILIBRE'), ('CREDICONTIGO', 'CREDICONTIGO'), ('KUPI', 'KUPI'), ('CREDISEGURO', 'CREDISEGURO')], default='SOLUCION INMEDIATA', verbose_name='Linea Credito'),
        ),
    ]
