# Generated by Django 5.0.6 on 2025-01-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0013_historicocredito_lineacredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocredito',
            name='amortizacion',
            field=models.CharField(choices=[('CUOTA FIJA', 'CUOTA FIJA'), ('CUOTA VARIABLE', 'CUOTA VARIABLE')], default='CUOTA FIJA', verbose_name='Amortización'),
        ),
    ]
