# Generated by Django 5.0.6 on 2024-08-09 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0013_historicosegurovida_fecharetiro'),
        ('parametro', '0006_tipoasociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoauxilio',
            name='tipoAuxilio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='parametro.tipoauxilio'),
            preserve_default=False,
        ),
    ]
