# Generated by Django 5.0.6 on 2025-01-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0014_historicocredito_amortizacion'),
        ('parametro', '0005_remove_tasasinterescredito_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocredito',
            name='tasaInteres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametro.tasasinterescredito'),
        ),
    ]
