# Generated by Django 5.0.6 on 2024-08-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0014_historicoauxilio_tipoauxilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpagos',
            name='diferencia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Diferencia'),
        ),
    ]
