# Generated by Django 5.0.6 on 2024-08-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0015_historialpagos_diferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoauxilio',
            name='anexoEight',
            field=models.CharField(default='Ejemplo', max_length=30, verbose_name='Anexo 8'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='anexoFive',
            field=models.CharField(default='Ejemplo', max_length=30, verbose_name='Anexo 5'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='anexoFour',
            field=models.CharField(default='Ejemplo', max_length=30, verbose_name='Anexo 4'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='anexoOne',
            field=models.CharField(default='Ejemplo', max_length=30, verbose_name='Anexo 1'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='anexoSeven',
            field=models.CharField(default='Ejemplo', max_length=30, verbose_name='Anexo 7'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='anexoSix',
            field=models.CharField(default='Ejemplo', max_length=30, verbose_name='Anexo 6'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='anexoThree',
            field=models.CharField(default='Ejemplo', max_length=30, verbose_name='Anexo 3'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='anexoTwo',
            field=models.CharField(default='Ejemplo', max_length=30, verbose_name='Anexo 2'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='nivelEducativo',
            field=models.CharField(default='Ejemplo', max_length=30, verbose_name='Nivel Educativo'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='nombre',
            field=models.CharField(default='Ejemplo', max_length=70, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='numDoc',
            field=models.CharField(default='Ejemplo', max_length=11, verbose_name='Número Documento'),
        ),
        migrations.AddField(
            model_name='historicoauxilio',
            name='parentesco',
            field=models.CharField(default='Ejemplo', max_length=20, verbose_name='Parentesco'),
        ),
    ]
