# Generated by Django 5.0.6 on 2025-01-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0015_historicocredito_tasainteres'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocredito',
            name='formaDesembolso',
            field=models.CharField(choices=[('TRANSFERENCIA ELECTRONICA', 'TRANSFERENCIA ELECTRONICA'), ('CHEQUE', 'CHEQUE'), ('CUENTA AHORROS', 'CUENTA AHORROS')], default='TRANSFERENCIA ELECTRONICA', verbose_name='Forma de Desembolso'),
        ),
        migrations.AddField(
            model_name='historicocredito',
            name='medioPago',
            field=models.CharField(choices=[('PAGO DIRECTO', 'PAGO DIRECTO'), ('NOMINA', 'NOMINA'), ('LIBRANZA', 'LIBRANZA')], default='PAGO DIRECTO', verbose_name='Medio de Pago'),
        ),
    ]
