# Generated by Django 5.0.6 on 2025-01-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0016_historicocredito_formadesembolso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocredito',
            name='totalCredito',
            field=models.IntegerField(default=10, verbose_name='Total Credito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicocredito',
            name='valorCuota',
            field=models.IntegerField(default=10, verbose_name='Valor Cuota'),
            preserve_default=False,
        ),
    ]
