# Generated by Django 5.0.6 on 2024-08-28 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0003_coohoperativitos'),
        ('historico', '0017_alter_historicoauxilio_anexoeight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoauxilio',
            name='parentesco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='beneficiario.parentesco'),
        ),
    ]
