# Generated by Django 5.0.6 on 2025-02-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0017_historicocredito_totalcredito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocredito',
            name='banco',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='historicocredito',
            name='numCuenta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero Cuenta'),
        ),
        migrations.AddField(
            model_name='historicocredito',
            name='tipoCuenta',
            field=models.CharField(blank=True, choices=[('CUENTA AHORROS', 'CUENTA AHORROS'), ('CUENTA CORRIENTE', 'CUENTA CORRIENTE')], default='CUENTA AHORROS', null=True, verbose_name='Tipo Cuenta'),
        ),
    ]
