# Generated by Django 5.0.6 on 2024-08-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0003_coohoperativitos'),
        ('historico', '0018_alter_historicoauxilio_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoEight',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Anexo 8'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoFive',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Anexo 5'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoFour',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Anexo 4'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoOne',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Anexo 1'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoSeven',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Anexo 7'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoSix',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Anexo 6'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoThree',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Anexo 3'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoTwo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Anexo 2'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='nivelEducativo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nivel Educativo'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='nombre',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='numDoc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Número Documento'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='parentesco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='beneficiario.parentesco'),
        ),
    ]
