# Generated by Django 5.0.6 on 2025-02-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0019_alter_historicocredito_lineacredito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocredito',
            name='cuotasPagas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicocredito',
            name='pendientePago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
