# Generated by Django 5.0.6 on 2024-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0019_alter_historicoauxilio_anexoeight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoauxilio',
            name='fechaDesembolso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Desembolso'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoEight',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 8'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoFive',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 5'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoFour',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 4'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoOne',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 1'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoSeven',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 7'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoSix',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 6'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoThree',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 3'),
        ),
        migrations.AlterField(
            model_name='historicoauxilio',
            name='anexoTwo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo 2'),
        ),
    ]
