# Generated by Django 5.0.6 on 2024-08-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0020_historicoauxilio_fechadesembolso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoauxilio',
            name='estado',
            field=models.CharField(choices=[('REVISION', 'REVISION'), ('OTORGADO', 'OTORGADO'), ('DENEGADO', 'DENEGADO')], default='REVISION', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicocredito',
            name='estado',
            field=models.CharField(choices=[('REVISION', 'REVISION'), ('OTORGADO', 'OTORGADO'), ('DENEGADO', 'DENEGADO')], default='REVISION', verbose_name='Estado'),
        ),
    ]
