# Generated by Django 5.0.6 on 2025-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0020_historicocredito_cuotaspagas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpagos',
            name='credito',
            field=models.IntegerField(blank=True, null=True, verbose_name='Credito'),
        ),
    ]
