# Generated by Django 5.0.6 on 2024-12-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
        ('historico', '0008_historialpagos_conveniopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codeudor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('tipoDocumento', models.CharField(choices=[('CEDULA', 'CEDULA'), ('REGISTRO CIVIL', 'REGISTRO CIVIL'), ('TARJETA IDENTIDAD', 'TARJETA IDENTIDAD'), ('CEDULA EXTRANJERA', 'CEDULA EXTRANJERA'), ('PASAPORTE', 'PASAPORTE'), ('PPT', 'PPT')], default='CEDULA')),
                ('numDocumento', models.CharField(max_length=11)),
                ('fechaExpedicion', models.DateField()),
                ('nacionalidad', models.CharField(max_length=30)),
                ('genero', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='MASCULINO')),
                ('estadoCivil', models.CharField(choices=[('SOLTERO', 'SOLTERO(A)'), ('CASADO', 'CASADO(A)'), ('UNION LIBRE', 'UNION LIBRE'), ('SEPARADO', 'SEPARADO(A)'), ('DIVORCIADO', 'DIVORCIADO(A)'), ('VIUDO', 'VIUDO(A)')], default='SOLTERO')),
                ('email', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField()),
                ('tipoVivienda', models.CharField(blank=True, choices=[('PROPIA', 'PROPIA'), ('FAMILIAR', 'FAMILIAR'), ('ARRENDADA', 'ARRENDADA')], default='PROPIA', null=True)),
                ('estrato', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('barrio', models.CharField(max_length=50)),
                ('numCelular', models.CharField(max_length=13)),
                ('ingresosTotales', models.IntegerField()),
                ('egresosTotales', models.IntegerField()),
                ('estadoRegistro', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('deptoResidencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deptoResidenciaCod', to='departamento.departamento')),
                ('dtoNacimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dtoNacimientoCod', to='departamento.departamento')),
                ('historicoCredito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='historico.historicocredito')),
                ('mpioDoc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.municipio')),
                ('mpioNacimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mpioNacimientoCod', to='departamento.municipio')),
                ('mpioResidencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mpioResidenciaCod', to='departamento.municipio')),
            ],
        ),
    ]
