# Generated by Django 5.0.6 on 2025-03-17 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credito', '0001_initial'),
        ('departamento', '0001_initial'),
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeudor',
            name='historicoCredito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='historico.historicocredito'),
        ),
        migrations.AddField(
            model_name='codeudor',
            name='mpioDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.municipio'),
        ),
        migrations.AddField(
            model_name='codeudor',
            name='mpioNacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mpioNacimientoCod', to='departamento.municipio'),
        ),
        migrations.AddField(
            model_name='codeudor',
            name='mpioResidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mpioResidenciaCod', to='departamento.municipio'),
        ),
    ]
