# Generated by Django 5.0.6 on 2024-12-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0033_delete_codeudor'),
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeudor',
            name='asociado',
            field=models.ForeignKey(default=327, on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado'),
            preserve_default=False,
        ),
    ]
