# Generated by Django 5.0.6 on 2026-02-09 16:04

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento_humano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='estado_registro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
