# Generated by Django 5.0.6 on 2026-02-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento_humano', '0002_empleados_estado_registro_empleados_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_registro', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='talento_humano.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='talento_humano.cargo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='talento_humano.empleados')),
                ('nombre_unidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='talento_humano.nombreunidad')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='talento_humano.tipocontrato')),
            ],
        ),
    ]
