# Generated by Django 5.0.6 on 2026-02-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento_humano', '0003_historiallaboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiallaboral',
            name='salario',
            field=models.IntegerField(),
        ),
    ]
