# Generated by Django 5.0.6 on 2026-02-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento_humano', '0004_alter_historiallaboral_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
