# Generated by Django 5.0.6 on 2026-02-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0026_remove_conveniosasociado_valor'),
        ('talento_humano', '0005_alter_empleados_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado'),
        ),
    ]
