# Generated by Django 5.0.6 on 2026-03-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talento_humano', '0006_empleados_asociado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NombreUnidad',
            new_name='Modalidad',
        ),
        migrations.RenameField(
            model_name='historiallaboral',
            old_name='nombre_unidad',
            new_name='modalidad',
        ),
    ]
