# Generated by Django 5.0.6 on 2026-03-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talento_humano', '0007_rename_nombreunidad_modalidad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='Contrato',
        ),
        migrations.RenameField(
            model_name='historiallaboral',
            old_name='area',
            new_name='contrato',
        ),
    ]
