# Generated by Django 5.0.6 on 2026-04-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento_humano', '0008_rename_area_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='MASCULINO', verbose_name='Genero'),
        ),
    ]
