# Generated by Django 5.0.6 on 2026-04-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talento_humano', '0009_empleados_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidad',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
