# Generated by Django 5.0.6 on 2026-04-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talento_humano', '0010_modalidad_abreviatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidad',
            name='abreviatura',
        ),
    ]
