# Generated by Django 5.0.6 on 2024-07-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoauxilio',
            name='valor',
            field=models.IntegerField(default=0, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
