# Generated by Django 5.0.6 on 2024-12-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0002_convenioasociado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConvenioAsociado',
            new_name='Convenio',
        ),
    ]
