# Generated by Django 5.0.6 on 2025-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0002_formapago_estadoregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoRadicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('ultimo_numero', models.IntegerField(default=0)),
            ],
        ),
    ]
