# Generated by Django 5.0.6 on 2025-10-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0003_consecutivoradicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consecutivoradicado',
            name='tipo',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='consecutivoradicado',
            unique_together={('tipo', 'anio')},
        ),
    ]
