# Generated by Django 5.0.6 on 2025-01-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0003_rename_convenioasociado_convenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasasInteresCredito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=30, verbose_name='Concepto')),
                ('valor', models.IntegerField(verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tasas Interes Credito',
                'verbose_name_plural': 'Tasas Interes Credito',
                'ordering': ['pk'],
            },
        ),
    ]
