# Generated by Django 5.0.6 on 2024-07-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0003_tarifas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesTarifa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=30, verbose_name='Concepto')),
                ('aporte', models.IntegerField(verbose_name='Aporte')),
                ('bSocial', models.IntegerField(verbose_name='Bienestar Social')),
            ],
            options={
                'verbose_name': 'Tarifa Por Mes',
                'verbose_name_plural': 'Tarifa Por Mes',
                'ordering': ['pk'],
            },
        ),
    ]
