# Generated by Django 5.0.6 on 2025-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0004_tasasinterescredito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasasinterescredito',
            name='valor',
        ),
        migrations.AddField(
            model_name='tasasinterescredito',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
