# Generated by Django 5.0.6 on 2025-10-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0004_consecutivoradicado_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consecutivoradicado',
            options={'verbose_name': 'Consecutivo de Radicado', 'verbose_name_plural': 'Consecutivos de Radicados'},
        ),
        migrations.AlterField(
            model_name='consecutivoradicado',
            name='anio',
            field=models.IntegerField(),
        ),
    ]
