# Generated by Django 5.0.6 on 2024-07-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0004_mestarifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formaPago', models.CharField(max_length=30, verbose_name='Forma Pago')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Forma de Pago',
                'ordering': ['pk'],
            },
        ),
    ]
