# Generated by Django 5.0.6 on 2025-01-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0005_remove_tasasinterescredito_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasasinterescredito',
            name='porcentaje',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
