# Generated by Django 5.0.6 on 2025-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0005_alter_consecutivoradicado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorcentajeDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('porcentaje', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
    ]
