# Generated by Django 5.0.6 on 2025-12-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0006_porcentajedescuento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PorcentajeDescuento',
            new_name='PorcentajeDescuentoAnticipo',
        ),
    ]
