# Generated by Django 5.0.6 on 2024-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0006_tipoasociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioFuneraria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=30, verbose_name='Servicio Funerario')),
            ],
            options={
                'verbose_name': 'Servicio Funeraria',
                'verbose_name_plural': 'Servicio Funeraria',
                'ordering': ['pk'],
            },
        ),
    ]
