# Generated by Django 5.0.6 on 2024-08-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0007_serviciofuneraria'),
    ]

    operations = [
        migrations.AddField(
            model_name='mestarifa',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Final'),
        ),
        migrations.AddField(
            model_name='mestarifa',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
