# Generated by Django 5.0.6 on 2025-02-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0007_alter_tasasinterescredito_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasasinterescredito',
            name='porcentaje',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
