# Generated by Django 5.0.6 on 2025-12-05 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0007_rename_porcentajedescuento_porcentajedescuentoanticipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PorcentajeDescuentoAnticipo',
            new_name='PorcentajeAnticipo',
        ),
    ]
