# Generated by Django 5.0.6 on 2025-02-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0008_alter_tasasinterescredito_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasasinterescredito',
            name='porcentaje',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
