# Generated by Django 5.0.6 on 2024-07-03 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('tipoDocumento', models.CharField(choices=[('CEDULA', 'Cedula'), ('REGISTRO CIVIL', 'Registro Civil'), ('TARJETA IDENTIDAD', 'Tarjeta Identidad'), ('CEDULA EXTRANJERA', 'Cedula Extranjera'), ('PASAPORTE', 'Pasaporte')], default='CEDULA', verbose_name='Tipo Documento')),
                ('numDocumento', models.CharField(max_length=10, verbose_name='Número Documento')),
                ('fechaExpedicion', models.DateField(verbose_name='Fecha Expedicion')),
                ('nacionalidad', models.CharField(max_length=30, verbose_name='Nacionalidad')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], default='MASCULINO', verbose_name='Genero')),
                ('estadoCivil', models.CharField(choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('UNION LIBRE', 'Union Libre')], default='SOLTERO', verbose_name='Estado Civil')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('numCelular', models.CharField(max_length=10, verbose_name='Numero Celular')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechaRetiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('deptoDoc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.departamento')),
                ('mpioDoc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.municipio')),
            ],
            options={
                'verbose_name': 'Asociado',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoVivienda', models.CharField(choices=[('PROPIA', 'Propia'), ('FAMILIAR', 'Familiar')], default='PROPIA', verbose_name='Tipo Vivienda')),
                ('estrato', models.IntegerField(verbose_name='Estrato')),
                ('direccion', models.CharField(max_length=30, verbose_name='Dirección')),
                ('barrio', models.CharField(max_length=30, verbose_name='barrio')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechaRetiro', models.DateField(blank=True, null=True, verbose_name='Fecha Retiro')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('deptoResidencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.departamento')),
                ('mpioResidencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.municipio')),
            ],
            options={
                'verbose_name': 'Residencia',
                'ordering': ['pk'],
            },
        ),
    ]
