# Generated by Django 5.0.6 on 2024-09-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='numResidencia',
            field=models.CharField(max_length=11, verbose_name='Numero Residencia'),
        ),
    ]
