# Generated by Django 5.0.6 on 2025-05-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0001_initial'),
        ('parametro', '0002_formapago_estadoregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniosasociado',
            name='primesMes',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.RESTRICT, to='parametro.mestarifa'),
            preserve_default=False,
        ),
    ]
