# Generated by Django 5.0.6 on 2024-07-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='fechaIngreso',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='fechaRetiro',
        ),
    ]
