# Generated by Django 5.0.6 on 2025-05-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0002_conveniosasociado_primesmes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conveniosasociado',
            old_name='primesMes',
            new_name='primerMes',
        ),
    ]
