# Generated by Django 5.0.6 on 2024-09-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0002_alter_asociado_numresidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='numCelular',
            field=models.CharField(max_length=11, verbose_name='Numero Celular'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='tituloPosgrado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo Posgrado'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='tituloPregrado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo Pregrado'),
        ),
        migrations.AlterField(
            model_name='laboral',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='laboral',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='laboral',
            name='nomRepresenLegal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Representante Legal'),
        ),
        migrations.AlterField(
            model_name='laboral',
            name='nombreEmpresa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='laboral',
            name='ocupacion',
            field=models.CharField(max_length=50, verbose_name='Ocupacion'),
        ),
        migrations.AlterField(
            model_name='referenciafamiliar',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='referenciafamiliar',
            name='numContacto',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='barrio',
            field=models.CharField(max_length=50, verbose_name='barrio'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
    ]
