# Generated by Django 5.0.6 on 2024-09-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0002_tarifaasociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroasociado',
            name='tarifaAsociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='asociado.tarifaasociado'),
        ),
    ]
