# Generated by Django 5.0.6 on 2024-10-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0002_alter_asociado_estadoasociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='numCelular',
            field=models.CharField(max_length=13, verbose_name='Numero Celular'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='numDocumento',
            field=models.CharField(max_length=11, verbose_name='Número Documento'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='numResidencia',
            field=models.CharField(max_length=13, verbose_name='Numero Residencia'),
        ),
    ]
