# Generated by Django 5.0.6 on 2025-08-06 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0003_rename_primesmes_conveniosasociado_primermes'),
        ('parametro', '0002_formapago_estadoregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenioHistoricoGasolina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_pagar', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('pendiente_pago', models.IntegerField(blank=True, null=True, verbose_name='Valor')),
                ('estado_registro', models.BooleanField(verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.convenio')),
                ('mes_tarifa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parametro.mestarifa')),
            ],
            options={
                'verbose_name': 'Convenio Chip Gasolina',
                'ordering': ['pk'],
            },
        ),
    ]
