# Generated by Django 5.0.6 on 2024-08-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0003_remove_asociado_deptodoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='estadoAsociado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('RETIRADO', 'Retirado')], default='ACTIVO', verbose_name='Estado Asociado'),
        ),
    ]
