# Generated by Django 5.0.6 on 2024-10-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0003_alter_asociado_numcelular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboral',
            name='telefono',
            field=models.CharField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
