# Generated by Django 5.0.6 on 2025-08-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0004_conveniohistoricogasolina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveniohistoricogasolina',
            name='convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.conveniosasociado'),
        ),
    ]
