# Generated by Django 5.0.6 on 2024-08-09 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0004_asociado_estadoasociado'),
        ('parametro', '0006_tipoasociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='tipoAsociado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='parametro.tipoasociado'),
            preserve_default=False,
        ),
    ]
