# Generated by Django 5.0.6 on 2024-08-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0005_asociado_tipoasociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='estadoCivil',
            field=models.CharField(choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('UNION LIBRE', 'Union Libre'), ('SEPADAO', 'Separado'), ('DIVORCIADO', 'Divorciado'), ('VIUDO', 'Viudo')], default='SOLTERO', verbose_name='Estado Civil'),
        ),
    ]
