# Generated by Django 5.0.6 on 2025-08-11 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0005_alter_conveniohistoricogasolina_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniohistoricogasolina',
            name='asociado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado'),
            preserve_default=False,
        ),
    ]
