# Generated by Django 5.0.6 on 2025-09-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0006_conveniohistoricogasolina_asociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='barrio',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='barrio'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='direccion',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Dirección'),
        ),
    ]
