# Generated by Django 5.0.6 on 2024-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0006_alter_asociado_estadocivil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='estadoAsociado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('RETIRADO', 'RETIRADO')], default='ACTIVO', verbose_name='Estado Asociado'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='estadoCivil',
            field=models.CharField(choices=[('SOLTERO', 'SOLTERO(A)'), ('CASADO', 'CASADO(A)'), ('UNION LIBRE', 'UNION LIBRE'), ('SEPARADO', 'SEPARADO(A)'), ('DIVORCIADO', 'DIVORCIADO(A)'), ('VIUDO', 'VIUDO(A)')], default='SOLTERO', verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='MASCULINO', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='tipoDocumento',
            field=models.CharField(choices=[('CEDULA', 'CEDULA'), ('REGISTRO CIVIL', 'REGISTRO CIVIL'), ('TARJETA IDENTIDAD', 'TARJETA IDENTIDAD'), ('CEDULA EXTRANJERA', 'CEDULA EXTRANJERA'), ('PASAPORTE', 'PASAPORTE')], default='CEDULA', verbose_name='Tipo Documento'),
        ),
    ]
