# Generated by Django 5.0.6 on 2024-11-14 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0007_remove_tarifaasociado_mascotaingreso_and_more'),
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='dtoNacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dtoNacimiento', to='departamento.departamento'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='mpioNacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mpioNacimiento', to='departamento.municipio'),
        ),
    ]
