# Generated by Django 5.0.6 on 2025-10-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0007_alter_asociado_barrio_alter_asociado_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='cabezaFamilia',
            field=models.CharField(blank=True, default='NO', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='asociado',
            name='empleadoCooho',
            field=models.CharField(blank=True, default='NO', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='asociado',
            name='nHijos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Hijos'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='nPersonasCargo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número Personas a Cargo'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='zonaUbidacion',
            field=models.CharField(blank=True, choices=[('RURAL', 'RURAL'), ('URBANA', 'URBANA')], default='URBANA', max_length=6, null=True),
        ),
    ]
