# Generated by Django 5.0.6 on 2024-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0007_alter_asociado_estadoasociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='tipoPersona',
            field=models.CharField(choices=[('PERSONA NATURAL', 'PERSONA NATURAL'), ('PERSONA JURIDICA', 'PERSONA JURIDICA')], default='PERSONA NATURAL', verbose_name='Tipo Persona'),
        ),
    ]
