# Generated by Django 5.0.6 on 2024-08-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0008_asociado_tipopersona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asociado',
            old_name='tipoPersona',
            new_name='tPersona',
        ),
    ]
