# Generated by Django 5.0.6 on 2024-11-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0008_asociado_dtonacimiento_asociado_fechanacimiento_and_more'),
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='barrio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='barrio'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='deptoResidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='deptoResidencia', to='departamento.departamento'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='estrato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estrato'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='mpioResidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mpioResidencia', to='departamento.municipio'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='tipoVivienda',
            field=models.CharField(blank=True, choices=[('PROPIA', 'PROPIA'), ('FAMILIAR', 'FAMILIAR'), ('ARRENDADA', 'ARRENDADA')], default='PROPIA', null=True, verbose_name='Tipo Vivienda'),
        ),
    ]
