# Generated by Django 5.0.6 on 2025-10-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0008_asociado_cabezafamilia_asociado_empleadocooho_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asociado',
            old_name='zonaUbidacion',
            new_name='zonaUbicacion',
        ),
    ]
