# Generated by Django 5.0.6 on 2025-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0009_rename_zonaubidacion_asociado_zonaubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboral',
            name='correoLaboral',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='declaraRenta',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', verbose_name='Declara Renta'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='nomJefeInmediato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Jefe Inmediato'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='ocupacionOtro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Otra Ocupacion'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='regimenTributario',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Regimen Tributario'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='responsableIva',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', verbose_name='Responsable IVA'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='telefonoJefeInmediato',
            field=models.CharField(blank=True, null=True, verbose_name='Telefono Jefe Inmediato'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='tipoContrato',
            field=models.CharField(blank=True, choices=[('INDEFINIDO', 'INDEFINIDO'), ('TERMINO FIJO', 'TERMINO FIJO'), ('OBRA O LABOR', 'OBRA O LABOR'), ('PRESTACION DE SERVICIOS', 'PRESTACION DE SERVICIOS'), ('HONORARIOS', 'HONORARIOS')], default='INDEFINIDO', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='laboral',
            name='tipoEmpresa',
            field=models.CharField(blank=True, choices=[('EMPRESA PUBLICA', 'EMPRESA PUBLICA'), ('EMPRESA PRIVADA', 'EMPRESA PRIVADA'), ('EMPRESA MIXTA', 'EMPRESA MIXTA'), ('OTRO', 'OTRO')], default='EMPRESA PUBLICA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laboral',
            name='tipoEmpresaOtro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Otro Tipo Empresa'),
        ),
        migrations.AlterField(
            model_name='laboral',
            name='ocupacion',
            field=models.CharField(blank=True, choices=[('ESTUDIANTE', 'ESTUDIANTE'), ('EMPLEADO', 'EMPLEADO'), ('PENSIONADO', 'PENSIONADO'), ('INDEPENDIENTE', 'INDEPENDIENTE'), ('COMERCIANTE', 'COMERCIANTE'), ('HOGAR', 'HOGAR'), ('CESANTE', 'CESANTE'), ('OTRO', 'OTRO')], default='EMPLEADO', max_length=50, null=True),
        ),
    ]
