# Generated by Django 5.0.6 on 2024-11-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0009_asociado_barrio_asociado_deptoresidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='numContacto',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='parentesco',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
    ]
