# Generated by Django 5.0.6 on 2025-10-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0010_laboral_correolaboral_laboral_declararenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financiera',
            name='egresos',
        ),
        migrations.RemoveField(
            model_name='financiera',
            name='ingresosActPrin',
        ),
        migrations.RemoveField(
            model_name='financiera',
            name='otroIngreso1',
        ),
        migrations.RemoveField(
            model_name='financiera',
            name='otroIngreso2',
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrAlimentacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egreso Alimentacion'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrAportesSalud',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egreso Aportes Salud'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrArrendamiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egreso Arrendamientos'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrCostos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egreso Costos y gastos ventas'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrDescripcionOtros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Descripcion Otros Egresos'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrEmbargos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egreso Embargo'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrObligaciones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egreso Obligaciones'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrOtros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egreso Otros'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrServiciosPublicos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egreso Arrendamientos'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrTarjetas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egreso Tarjeta Credito'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='egrTransporte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Egreso Transporte'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrArrendamientos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso Arrendamientos'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrCompensacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso Compensacion'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrDescripcionOtros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Descripcion Otros Ingresos'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrGiros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso Giros'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrHonorarios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso Honorarios'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrHorasExtras',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso Horas Extras'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrIntereses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso Intereses'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrOtros',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso Otros'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrPension',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso Pension'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrSalario',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso Salario'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='ingrVentas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso Ventas'),
        ),
    ]
