# Generated by Django 5.0.6 on 2024-11-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0010_asociado_numcontacto_asociado_parentesco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboral',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ocupacion'),
        ),
    ]
