# Generated by Django 5.0.6 on 2024-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0010_asociado_dtonacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociado',
            name='dtoNacimiento',
        ),
        migrations.RemoveField(
            model_name='asociado',
            name='fechaNacimiento',
        ),
        migrations.AddField(
            model_name='asociado',
            name='numResidencia',
            field=models.CharField(default=3333333, max_length=10, verbose_name='Numero Residencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residencia',
            name='tipoVivienda',
            field=models.CharField(choices=[('PROPIA', 'PROPIA'), ('FAMILIAR', 'FAMILIAR'), ('ARRENDADA', 'ARRENDADA')], default='PROPIA', verbose_name='Tipo Vivienda'),
        ),
    ]
