# Generated by Django 5.0.6 on 2024-08-15 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0011_remove_asociado_dtonacimiento_and_more'),
        ('departamento', '0002_paisrepatriacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('dtoNacimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.departamento')),
                ('mpioNacimiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.municipio')),
            ],
            options={
                'verbose_name': 'Fecha Nacimiento',
                'ordering': ['pk'],
            },
        ),
    ]
