# Generated by Django 5.0.6 on 2025-10-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0011_remove_financiera_egresos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboral',
            name='tipoCuenta',
            field=models.CharField(blank=True, choices=[('CUENTA AHORROS', 'CUENTA AHORROS'), ('CUENTA CORRIENTE', 'CUENTA CORRIENTE')], null=True, verbose_name='Tipo Cuenta'),
        ),
        migrations.AlterField(
            model_name='laboral',
            name='tipoEmpresa',
            field=models.CharField(blank=True, choices=[('PUBLICA', 'PUBLICA'), ('PRIVADA', 'PRIVADA'), ('MIXTA', 'MIXTA'), ('OTRO', 'OTRO')], default='PUBLICA', max_length=50, null=True),
        ),
    ]
