# Generated by Django 5.0.6 on 2024-11-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0011_alter_laboral_ocupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='nombreRF',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
