# Generated by Django 5.0.6 on 2025-10-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0012_alter_laboral_tipocuenta_alter_laboral_tipoempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiera',
            name='operacionesMoneda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Moneda Extranjera'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='operacionesMonedaCuales',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Operaciones Moneda Cuales'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='operacionesMonedaExtranjera',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', verbose_name='Operaciones Moneda Extranjera'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='operacionesMonedaMonto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='operacionesMonedaTipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo producto u operacion'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='poseeCuentasBanco',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', verbose_name='Posee Cuentas en Otros Bancos'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='poseeCuentasCiudad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='poseeCuentasCuenta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cuenta'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='poseeCuentasMoneda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='poseeCuentasMonedaExtranjera',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', verbose_name='Posee Cuentas Moneda Extranjera'),
        ),
        migrations.AddField(
            model_name='financiera',
            name='poseeCuentasPais',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais'),
        ),
    ]
