# Generated by Django 5.0.6 on 2024-11-20 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0012_asociado_nombrerf_alter_asociado_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepatriacionTitular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRepatriacion', models.DateField(verbose_name='Fecha Repatriacion')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Repatriacion Titular',
                'ordering': ['pk'],
            },
        ),
    ]
