# Generated by Django 5.0.6 on 2024-08-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0012_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociado',
            name='estadoAsociado',
        ),
        migrations.RemoveField(
            model_name='asociado',
            name='tipoAsociado',
        ),
    ]
