# Generated by Django 5.0.6 on 2024-08-15 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0013_remove_asociado_estadoasociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacimiento',
            name='asociado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nacimiento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
