# Generated by Django 5.0.6 on 2025-10-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0013_financiera_operacionesmoneda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiera',
            name='poseeCuentasBanco',
            field=models.CharField(max_length=50, verbose_name='Posee Cuentas en Otros Bancos'),
        ),
    ]
