# Generated by Django 5.0.6 on 2025-10-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0014_alter_financiera_poseecuentasbanco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financiera',
            name='activos',
        ),
        migrations.RemoveField(
            model_name='financiera',
            name='pasivos',
        ),
        migrations.RemoveField(
            model_name='financiera',
            name='patrimonio',
        ),
        migrations.AlterField(
            model_name='financiera',
            name='operacionesMonedaExtranjera',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', null=True, verbose_name='Operaciones Moneda Extranjera'),
        ),
        migrations.AlterField(
            model_name='financiera',
            name='poseeCuentasBanco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Posee Cuentas en Otros Bancos'),
        ),
        migrations.AlterField(
            model_name='financiera',
            name='poseeCuentasMonedaExtranjera',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', null=True, verbose_name='Posee Cuentas Moneda Extranjera'),
        ),
    ]
