# Generated by Django 5.0.6 on 2024-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0014_nacimiento_asociado_alter_nacimiento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='envioInfoCorreo',
            field=models.BooleanField(default=False, verbose_name='Envio Información Email'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='envioInfoMensaje',
            field=models.BooleanField(default=False, verbose_name='Envio Información Mensaje Texto'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='envioInfoWhatsapp',
            field=models.BooleanField(default=True, verbose_name='Envio Información WhatsApp'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='nivelEducativo',
            field=models.CharField(choices=[('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('TECNICO', 'TECNICO'), ('TECNOLOGICO', 'TECNOLOGICO'), ('PREGRADO', 'PREGRADO'), ('ESPECIALIZACION', 'ESPECIALIZACION'), ('MAESTRIA', 'MAESTRIA'), ('DOCTORADO', 'DOCTORADO')], default='SECUNDARIA', verbose_name='Nivel Educativo'),
        ),
    ]
