# Generated by Django 5.0.6 on 2024-11-20 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0014_repatriaciontitular_paisrepatriacion'),
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repatriaciontitular',
            name='PaisRepatriacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='departamento.paisrepatriacion'),
        ),
    ]
