# Generated by Django 5.0.6 on 2024-11-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0015_alter_repatriaciontitular_paisrepatriacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repatriaciontitular',
            old_name='PaisRepatriacion',
            new_name='paisRepatriacion',
        ),
    ]
