# Generated by Django 5.0.6 on 2024-08-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0015_asociado_envioinfocorreo_asociado_envioinfomensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='tituloPosgrado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Titulo Posgrado'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='tituloPregrado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Titulo Pregrado'),
        ),
    ]
