# Generated by Django 5.0.6 on 2025-10-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0015_remove_financiera_activos_remove_financiera_pasivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiera',
            name='egrDescripcionOtros',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Descripcion Otros Egresos'),
        ),
        migrations.AlterField(
            model_name='financiera',
            name='ingrDescripcionOtros',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Descripcion Otros Ingresos'),
        ),
    ]
