# Generated by Django 5.0.6 on 2024-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0016_asociado_tituloposgrado_asociado_titulopregrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='tituloPosgrado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo Posgrado'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='tituloPregrado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo Pregrado'),
        ),
    ]
