# Generated by Django 5.0.6 on 2024-11-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0017_alter_repatriaciontitular_paisrepatriacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nacimiento',
        ),
    ]
