# Generated by Django 5.0.6 on 2024-08-16 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0017_alter_asociado_tituloposgrado_and_more'),
        ('departamento', '0002_paisrepatriacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ocupacion', models.CharField(max_length=30, verbose_name='Ocupacion')),
                ('nombreEmpresa', models.CharField(blank=True, null=True, verbose_name='Nombre Empresa')),
                ('cargo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dirección')),
                ('nomRepresenLegal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Representante Legal')),
                ('numDocRL', models.IntegerField(blank=True, null=True, verbose_name='Numero Documento Representante')),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fechaTerminacion', models.DateField(blank=True, null=True, verbose_name='Fecha Terminacion')),
                ('direccion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Direccion')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('admRP', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', verbose_name='Administra RP')),
                ('pep', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', verbose_name='PEP')),
                ('activEcono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Actividad Economica')),
                ('ciiu', models.CharField(blank=True, max_length=6, null=True, verbose_name='CIIU')),
                ('banco', models.CharField(blank=True, max_length=30, null=True, verbose_name='Banco')),
                ('numCuenta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero Cuenta')),
                ('tipoCuenta', models.CharField(blank=True, choices=[('CUENTA AHORROS', 'CUENTA AHORROS'), ('CUENTA CORRIENTE', 'CUENTA CORRIENTE')], default='CUENTA AHORROS', null=True, verbose_name='Tipo Cuenta')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('dptoTrabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='departamento.departamento')),
                ('mpioTrabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='departamento.municipio')),
            ],
            options={
                'verbose_name': 'Laboral',
                'ordering': ['pk'],
            },
        ),
    ]
