# Generated by Django 5.0.6 on 2025-10-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0017_rename_telefono_laboral_telefonolaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='fechaActualizacionDatos',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Actualizacion Datos'),
        ),
    ]
