# Generated by Django 5.0.6 on 2024-11-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0018_delete_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='asociado',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='deptoResidencia',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='mpioResidencia',
        ),
        migrations.DeleteModel(
            name='ReferenciaFamiliar',
        ),
        migrations.DeleteModel(
            name='Residencia',
        ),
    ]
