# Generated by Django 5.0.6 on 2024-08-17 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0018_laboral'),
        ('parametro', '0007_serviciofuneraria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroAsociado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametro.tipoasociado')),
            ],
        ),
    ]
