# Generated by Django 5.0.6 on 2025-10-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0018_asociado_fechaactualizaciondatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadicadoAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('VINCULACION', 'Vinculación'), ('ACTUALIZACION', 'Actualización')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radicados', to='asociado.asociado')),
            ],
        ),
    ]
