# Generated by Django 5.0.6 on 2024-11-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0019_remove_residencia_asociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repatriaciontitular',
            name='fechaRetiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Retiro'),
        ),
    ]
