# Generated by Django 5.0.6 on 2025-10-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0019_radicadoasociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicadoasociado',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
    ]
