# Generated by Django 5.0.6 on 2024-08-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0019_parametroasociado'),
        ('parametro', '0007_serviciofuneraria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametroasociado',
            options={'ordering': ['pk'], 'verbose_name': 'Parametros Asociado'},
        ),
        migrations.AddField(
            model_name='parametroasociado',
            name='funeraria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='parametro.serviciofuneraria'),
            preserve_default=False,
        ),
    ]
