# Generated by Django 5.0.6 on 2024-08-20 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0020_alter_parametroasociado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingresosActPrin', models.IntegerField(blank=True, null=True, verbose_name='Ingresos Actividad Principal')),
                ('otroIngreso1', models.IntegerField(blank=True, null=True, verbose_name='Otros Ingresos 1')),
                ('otroIngreso2', models.IntegerField(blank=True, null=True, verbose_name='Otros Ingresos 2')),
                ('egresos', models.IntegerField(blank=True, null=True, verbose_name='Total Egresos')),
                ('pasivos', models.IntegerField(blank=True, null=True, verbose_name='Total Pasivos')),
                ('patrimonio', models.IntegerField(blank=True, null=True, verbose_name='Total Patrimonio')),
                ('totalActivos', models.IntegerField(blank=True, null=True, verbose_name='Egresos')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Información Financiera',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaFamiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(blank=True, null=True, verbose_name='Nombre')),
                ('parentesco', models.CharField(blank=True, null=True, verbose_name='Parentesco')),
                ('numContacto', models.IntegerField(blank=True, null=True, verbose_name='Número Contacto')),
                ('estadoRegistro', models.BooleanField(verbose_name='Estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='asociado.asociado')),
            ],
            options={
                'verbose_name': 'Referencia Familiar',
                'ordering': ['pk'],
            },
        ),
    ]
