# Generated by Django 5.0.6 on 2024-12-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0020_repatriaciontitular_fecharetiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='repatriaciontitular',
            name='ciudadRepatriacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad Repatriacion'),
        ),
    ]
