# Generated by Django 5.0.6 on 2025-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0020_alter_radicadoasociado_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radicadoasociado',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='radicadoasociado',
            name='proceso',
            field=models.CharField(blank=True, choices=[('VINCULACION', 'Vinculación'), ('ACTUALIZACION', 'Actualización de datos'), ('SOLICITUD', 'Solicitud general')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='radicadoasociado',
            name='tipo',
            field=models.CharField(blank=True, choices=[('RA', 'Registro Asociado'), ('RSE', 'Registro Servicios Exequiales'), ('SAE', 'Solicitud Auxilio Económico'), ('FEP', 'Formato Extracto Pago'), ('FSC', 'Formato Solicitud Crédito')], max_length=10, null=True),
        ),
    ]
