# Generated by Django 5.0.6 on 2025-10-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0021_rename_fecha_radicadoasociado_fecha_creacion_and_more'),
        ('parametro', '0005_alter_consecutivoradicado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifaasociado',
            name='cuotaRepatriacion',
        ),
        migrations.AddField(
            model_name='repatriaciontitular',
            name='primerMes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='repatriaciones_titular', to='parametro.mestarifa'),
        ),
        migrations.AddField(
            model_name='tarifaasociado',
            name='cuotaRepatriacionBeneficiarios',
            field=models.IntegerField(blank=True, null=True, verbose_name='Repatriacion Beneficiarios'),
        ),
        migrations.AddField(
            model_name='tarifaasociado',
            name='cuotaRepatriacionTitular',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Repatriacion Titular'),
        ),
    ]
