# Generated by Django 5.0.6 on 2025-10-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0022_remove_tarifaasociado_cuotarepatriacion_and_more'),
        ('parametro', '0005_alter_consecutivoradicado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaasociado',
            name='primerMesCuotaAdicional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tarifa_asociado', to='parametro.mestarifa'),
        ),
    ]
