# Generated by Django 5.0.6 on 2024-08-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0022_remove_financiera_totalactivos_financiera_activos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referenciafamiliar',
            old_name='nombreEmpresa',
            new_name='nombre',
        ),
    ]
