# Generated by Django 5.0.6 on 2024-08-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0023_rename_nombreempresa_referenciafamiliar_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciafamiliar',
            name='numContacto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
