# Generated by Django 5.0.6 on 2025-11-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0023_tarifaasociado_primermescuotaadicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='numResidencia',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Numero Residencia'),
        ),
    ]
