# Generated by Django 5.0.6 on 2024-12-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0023_conveniosasociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaasociado',
            name='cuotaConvenio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Convenio'),
        ),
    ]
