# Generated by Django 5.0.6 on 2025-11-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0024_alter_asociado_numresidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniosasociado',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
