# Generated by Django 5.0.6 on 2024-08-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0024_alter_referenciafamiliar_numcontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenciafamiliar',
            name='numContacto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
    ]
