# Generated by Django 5.0.6 on 2025-11-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0025_conveniosasociado_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conveniosasociado',
            name='valor',
        ),
    ]
