# Generated by Django 5.0.6 on 2024-12-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0025_remove_tarifaasociado_adicionalingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifaasociado',
            name='fechaInicioAdicional',
        ),
    ]
