# Generated by Django 5.0.6 on 2024-08-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0025_alter_referenciafamiliar_numcontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroasociado',
            name='autorizaciondcto',
            field=models.BooleanField(default=True, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
