# Generated by Django 5.0.6 on 2024-08-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0026_parametroasociado_autorizaciondcto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroasociado',
            name='autorizaciondcto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Estado'),
        ),
    ]
