# Generated by Django 5.0.6 on 2026-04-06 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0026_remove_conveniosasociado_valor'),
        ('parametro', '0008_rename_porcentajedescuentoanticipo_porcentajeanticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repatriaciontitular',
            name='ultimoMes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='repatriacion_titular_retiro', to='parametro.mestarifa'),
        ),
    ]
