# Generated by Django 5.0.6 on 2024-12-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0026_remove_tarifaasociado_fechainicioadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaasociado',
            name='fechaInicioAdicional',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Adicional'),
        ),
    ]
