# Generated by Django 5.0.6 on 2024-12-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0027_tarifaasociado_fechainicioadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaasociado',
            name='estadoAdicional',
            field=models.BooleanField(default=False, verbose_name='Estado Adicional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarifaasociado',
            name='fechaFinAdicional',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Adicional'),
        ),
    ]
