# Generated by Django 5.0.6 on 2026-04-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0027_repatriaciontitular_ultimomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='repatriaciontitular',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
