# Generated by Django 5.0.6 on 2024-08-22 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0027_alter_parametroasociado_autorizaciondcto'),
        ('parametro', '0007_serviciofuneraria'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='tAsociado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='parametro.tipoasociado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referenciafamiliar',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='referenciafamiliar',
            name='parentesco',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Parentesco'),
        ),
    ]
