# Generated by Django 5.0.6 on 2026-04-06 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0028_repatriaciontitular_anulado'),
        ('parametro', '0008_rename_porcentajedescuentoanticipo_porcentajeanticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaasociado',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarifaasociado',
            name='ultimoMesSeguroVida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='valor_adicional_retiro', to='parametro.mestarifa'),
        ),
    ]
