# Generated by Django 5.0.6 on 2024-12-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0028_tarifaasociado_estadoadicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaasociado',
            name='conceptoAdicional',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Concepto Adicional'),
        ),
    ]
