# Generated by Django 5.0.6 on 2024-08-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0029_asociado_estadoasociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'CEDULA'), ('REGISTRO CIVIL', 'REGISTRO CIVIL'), ('TARJETA IDENTIDAD', 'TARJETA IDENTIDAD'), ('CEDULA EXTRANJERA', 'CEDULA EXTRANJERA'), ('PASAPORTE', 'PASAPORTE')], default='CC', verbose_name='Tipo Documento'),
        ),
    ]
