# Generated by Django 5.0.6 on 2026-04-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0029_tarifaasociado_anulado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifaasociado',
            old_name='ultimoMesSeguroVida',
            new_name='ultimoMesCuotaAdicional',
        ),
    ]
