# Generated by Django 5.0.6 on 2024-12-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0030_codeudor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeudor',
            name='numResidencia',
        ),
        migrations.AddField(
            model_name='codeudor',
            name='egresosTotales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codeudor',
            name='ingresosTotales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
