# Generated by Django 5.0.6 on 2026-04-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0030_rename_ultimomessegurovida_tarifaasociado_ultimomescuotaadicional'),
        ('parametro', '0008_rename_porcentajedescuentoanticipo_porcentajeanticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveniosasociado',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conveniosasociado',
            name='ultimoMes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='convenio_retiro', to='parametro.mestarifa'),
        ),
    ]
