# Generated by Django 5.0.6 on 2024-08-29 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0031_alter_asociado_tipodocumento'),
        ('parametro', '0008_mestarifa_fechafinal_mestarifa_fechainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroasociado',
            name='primerMes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='parametro.mestarifa'),
        ),
    ]
