# Generated by Django 5.0.6 on 2024-12-16 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0031_remove_codeudor_numresidencia_and_more'),
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeudor',
            name='barrio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='deptoResidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deptoResidenciaCod', to='departamento.departamento'),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='dtoNacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dtoNacimientoCod', to='departamento.departamento'),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='egresosTotales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='estrato',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='ingresosTotales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='mpioNacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mpioNacimientoCod', to='departamento.municipio'),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='mpioResidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mpioResidenciaCod', to='departamento.municipio'),
        ),
    ]
