# Generated by Django 5.0.6 on 2024-12-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0032_alter_codeudor_barrio_alter_codeudor_deptoresidencia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Codeudor',
        ),
    ]
