# Generated by Django 5.0.6 on 2025-02-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0033_delete_codeudor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiera',
            name='asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='financiera', to='asociado.asociado'),
        ),
    ]
