# Generated by Django 5.0.6 on 2025-02-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0034_alter_financiera_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='indicativoCelular',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Indicativo Celular'),
        ),
    ]
