# Generated by Django 5.0.6 on 2025-02-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0035_asociado_indicativocelular'),
        ('departamento', '0003_alter_pais_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='indicativoCelular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='departamento.pais'),
        ),
    ]
