# Generated by Django 5.0.6 on 2025-02-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0037_parametroasociado_vinculacioncuotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroasociado',
            name='vinculacionPendientePago',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vinculacion valor'),
        ),
    ]
