# Generated by Django 5.0.6 on 2025-02-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0038_parametroasociado_vinculacionpendientepago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametroasociado',
            name='empresa',
        ),
    ]
